name: CI

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install dependencies
        run: npm install
        working-directory: src

      - name: Fix Jest permissions
        run: chmod +x node_modules/.bin/jest

      - name: Run tests with coverage
        run: npm run test -- --coverage

      - name: Enforce coverage threshold
        run: |
          coverage=$(grep -Po 'All files.*\K\d+(?=%)' coverage/lcov-report/index.html || echo 0)
          echo "Coverage detected: $coverage%"
          if [ "$coverage" -lt "80" ]; then
            echo "Coverage below 80%. Failing the build."
            exit 1
          fi
